### ISSUE TITLE
Crash when compiling with MSYS2 on Windows 10

### ISSUE THREAD

**Issue by caecos** [dplduffy/DFYM#1]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
parse error: Invalid numeric literal at line 20, column 22
parse error: Invalid numeric literal at line 20, column 22
C:/msys64/Rack-SDK/plugin.mk:9: *** SLUG could not be found in manifest. Arrêt.

**Comment by vcvrackideas** [comment]
Same for me

**Comment by dplduffy** [comment]
should be fixed with latest push. not sure what happened there.

**Comment by caecos** [comment]
Fine, build ok...regards...
